# Site settings
title: Mayur
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  mayurkumar patel, full stack developer
baseurl:
url: "http://mayurkumar.info" # the base hostname & protocol for your site
twitter_username: jlmayur
github_username:  charusat09

# Build settings
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-seo-tag

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


# collections:
#   portfolio:
#     output: true
#     permalink: /portfolio/:path/
#   poetry:
#     output: true
#     permalink: /poetry/:path/
